version: 2
updates:
  # Docker 섹션 제거
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
