version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"   # 모든 워크플로우 감시
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ deps"
    labels:
      - "dependencies"
      - "github-actions"
