extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start:
    present: false
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  comments:
    require-starting-space: false
  trailing-spaces:
    level: warning
  brackets:
    max-spaces-inside: 1
    level: warning
