version: "3.9"

services:
  defender_bot:
    build: .
    container_name: defender-bot
    restart: always
    volumes:
      - ./app:/home/defender/app
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    depends_on:
      - mysql
    networks:
      - defender-net

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: defenderdb
      MYSQL_USER: defender
      MYSQL_PASSWORD: defenderpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - defender-net

volumes:
  mysql-data:

networks:
  defender-net:
