# .github/workflows/auto-backup2.yml
name: Automatic Financial Backup (Manual + Cron) # 워크플로우 이름

# 5번째 줄이었던 'id: auto-financial-backup-workflow' 이 부분을 제거합니다.
# 워크플로우 수준에서는 'id' 필드를 직접 선언하지 않습니다.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 매일 자정 (UTC)
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Current retry attempt count'
        required: false
        default: '0'
        type: string # 숫자로 사용하지만, 입력은 문자열로 받음
      triggered_by_workflow_id:
        description: 'ID of the workflow run that triggered this retry'
        required: false
        default: ''
        type: string

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 백업 작업에 쓰기 권한이 필요할 경우 추가
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Perform Backup
        run: |
          echo "Performing financial backup for auto-backup2..."
          # 여기에 실제 백업 로직을 추가
          # 예: rsync -avz --delete /path/to/source /path/to/destination
          # 예: aws s3 sync /path/to/local s3://your-backup-bucket
          
          # 테스트를 위해 의도적으로 실패를 시뮬레이션하고 싶다면 아래 주석을 해제
          # exit 1 
          echo "Backup successful!"
