# .github/workflows/auto-backup.yml (원본 워크플로우 파일)
name: Automatic Financial Backup (Manual + Cron) # 워크플로우 이름

# 이 줄을 추가하거나, 기존 name 바로 아래에 'id' 필드를 추가합니다.
name:auto-financial-backup-workflow 

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 매일 자정 (UTC)
  workflow_dispatch:
    inputs: # 재시도 워크플로우가 이 인풋을 통해 재시도 횟수 등을 전달
      retry_count:
        description: 'Current retry attempt count'
        required: false
        default: '0'
        type: string # 숫자로 사용하지만, 입력은 문자열로 받음
      triggered_by_workflow_id:
        description: 'ID of the workflow run that triggered this retry'
        required: false
        default: ''
        type: string

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # ... (기존 백업 로직)
      - name: Perform Backup
        run: |
          echo "Performing financial backup..."
          # 의도적으로 실패를 시뮬레이션
          # exit 1 # 테스트를 위해 주석 해제하여 실패 유도
          echo "Backup successful!"
