# .github/workflows/build_and_test.yml
name: Swift CLI Build and Test

on:
  push:
    branches:
      - main
      - develop # 주 개발 브랜치 추가 (예: develop)
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest # macOS 환경에서 테스트하려면 'macos-latest'로 변경

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 최신 checkout 액션 사용

    - name: Install Swift Toolchain
      # swift-actions/setup-swift@v2 액션은 'latest' 대신 특정 버전 번호를 요구합니다.
      # 현재 안정적인 최신 Swift 버전 (예: 5.10)을 사용하거나,
      # 프로젝트에 필요한 정확한 버전을 명시하는 것이 좋습니다.
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10' # <--- 이 부분을 안정적인 특정 Swift 버전으로 변경해주세요.
                              # 예: '5.10', '5.9', '6.0' (베타/릴리즈 시)

    - name: Build Debug Configuration
      # Package.swift 파일이 리포지토리의 루트 디렉토리에 있다고 가정합니다.
      # 만약 Package.swift가 하위 디렉토리 (예: `my-app/Package.swift`)에 있다면,
      # `run: cd my-app && swift build` 와 같이 경로를 변경해야 합니다.
      run: swift build

    - name: Run Tests
      # Package.swift 파일이 리포지토리의 루트 디렉토리에 있다고 가정합니다.
      run: swift test

    # Optional: Release 모드로도 빌드하여 컴파일 오류가 없는지 확인합니다.
    - name: Build Release Configuration
      run: swift build -c release
