# .github/workflows/build_and_test.yml
name: Swift CLI Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Swift 5.10 (Manual)
      run: |
        SWIFT_VERSION="5.10"
        SWIFT_RELEASE="5.10-RELEASE" # Match the release name from swift.org
        # Adjust URL based on official Swift.org downloads for Ubuntu 22.04
        SWIFT_DOWNLOAD_URL="https://download.swift.org/swift-${SWIFT_VERSION}-release/ubuntu2204/swift-${SWIFT_RELEASE}/swift-${SWIFT_RELEASE}-ubuntu22.04.tar.gz"
        SWIFT_TARBALL="swift-${SWIFT_RELEASE}-ubuntu22.04.tar.gz"
        SWIFT_EXTRACT_DIR="/opt/swift" # Where Swift will be installed

        echo "Downloading Swift ${SWIFT_VERSION}..."
        wget -q ${SWIFT_DOWNLOAD_URL} -O ${SWIFT_TARBALL}

        echo "Extracting Swift to ${SWIFT_EXTRACT_DIR}..."
        sudo mkdir -p ${SWIFT_EXTRACT_DIR}
        sudo tar -xzf ${SWIFT_TARBALL} -C ${SWIFT_EXTRACT_DIR} --strip-components=1

        echo "Adding Swift to PATH"
        echo "${SWIFT_EXTRACT_DIR}/usr/bin" >> $GITHUB_PATH

        # Clean up
        rm ${SWIFT_TARBALL}

        echo "Swift installation complete."
        swift --version
      # You can add -e for exiting on error if preferred, but for debugging, sometimes it's good to see all output.

    - name: Build Debug Configuration
      run: swift build

    - name: Run Tests
      run: swift test

    - name: Build Release Configuration (Optional)
      run: swift build -c release
