name: Codex Cost Check
on:
  workflow_dispatch:

jobs:
  check-cost:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MASKED_CARD: "**** **** **** 7206"
    steps:
      - name: Fetch Codex usage
        id: fetch
        run: |
          curl --fail --silent https://api.openai.com/v1/usage \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -o usage.json
          if jq -e '.total_usage' usage.json >/dev/null; then
            total=$(jq '.total_usage' usage.json)
            echo "total_usage=$total" >> $GITHUB_OUTPUT
          else
            echo "total_usage=0" >> $GITHUB_OUTPUT
          fi
      - name: Check charges
        run: |
          total=${{ steps.fetch.outputs.total_usage }}
          if [ "$total" -gt 0 ]; then
            echo "Codex usage detected. Charges may be billed to card $MASKED_CARD."
          else
            echo "No Codex usage detected. Card $MASKED_CARD will not be charged."
          fi
