name: 🧪 Unit Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set executable permissions
        run: chmod +x ./run-tests.sh

      - name: Run tests
        run: ./run-tests.sh
