# 목적: main 브랜치에 push 시 자동 테스트 실행
name: CI Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests..."
          ./run-tests.sh
