name: 🧹 파일명에 .md가 포함된 모든 파일 삭제

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🗑️ 파일명에 '.md'가 포함된 모든 파일 삭제
        run: |
          echo "echo '[🗑️] 파일명에 .md가 포함된 모든 파일 삭제 시작...'"
          echo '[🗑️] 파일명에 .md가 포함된 모든 파일 삭제 시작...'
          find . -type f -name '*md*' -print -exec echo "rm {}" \; -exec rm {} \;
          echo "echo '[🗑️] 삭제 완료!'"
          echo '[🗑️] 삭제 완료!'
