name: 🧹 README.md 파일 삭제

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🗑️ 모든 디렉토리의 README.md 파일 삭제
        run: |
          echo "echo '[🗑️] 모든 디렉토리의 README.md 파일 삭제 시작...'"
          echo '[🗑️] 모든 디렉토리의 README.md 파일 삭제 시작...'
          find . -type f -name 'README.md' -print -exec echo "rm {}" \; -exec rm {} \;
          echo "echo '[🗑️] 삭제 완료!'"
          echo '[🗑️] 삭제 완료!'
