# .github/workflows/delete_workflow_file.yml
name: Delete Specific Workflow File

on:
  # This workflow is designed to be manually triggered.
  # When you run it from the GitHub Actions UI, you can specify
  # which file to delete.
  workflow_dispatch:
    inputs:
      file_to_delete:
        description: '삭제할 워크플로우 파일의 경로 (예: .github/workflows/잘못된_파일_이름.yml)'
        required: true
        # >>>>> 중요: 여기에 삭제하려는 파일의 정확한 경로를 입력하세요. <<<<<
        # 예를 들어, 실제 파일 이름이 'my_rust_ci.yml'이라면 '.github/workflows/my_rust_ci.yml'로 변경해야 합니다.
        default: '.github/workflows/rustci.yml' # <--- 이 부분이 현재 문제의 원인일 가능성이 높습니다.
                                                #      이 경로가 실제 GitHub repo에 있는지 다시 확인해주세요.

jobs:
  delete_file_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is CRITICAL for file deletion. Use with extreme caution!

    steps:
    - name: Checkout repository
      # Checkout the repository to get access to its files,
      # which is necessary for retrieving the file's SHA.
      uses: actions/checkout@v4

    - name: Get file SHA
      id: get_sha
      # Fetch the SHA of the file to be deleted.
      # The GitHub API requires the file's current SHA for deletion.
      run: |
        FILE_PATH="${{ github.event.inputs.file_to_delete }}"
        REPO_OWNER="${{ github.repository_owner }}"
        REPO_NAME="${{ github.event.repository.name }}"
        
        # Use curl to get file metadata, including its SHA
        # jq is used for JSON parsing, which is usually pre-installed on GitHub Actions runners.
        # We also explicitly specify the 'main' branch in the API call, just to be sure.
        SHA=$(curl -s \
                   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/contents/$FILE_PATH?ref=refs/heads/main" | jq -r '.sha')
        
        if [ "$SHA" == "null" ]; then
          echo "::error::Error: 파일 '$FILE_PATH'을(를) 찾을 수 없거나 SHA를 가져올 수 없습니다. 경로가 정확한지, 파일이 존재하는지 확인하세요."
          exit 1
        fi
        echo "Successfully retrieved SHA for $FILE_PATH: $SHA"
        echo "file_sha=$SHA" >> "$GITHUB_OUTPUT" # Set output for subsequent steps
      env:
        # GITHUB_TOKEN is automatically provided by GitHub Actions for the current repository.
        # It needs 'contents: write' permission as defined in the 'permissions' block above.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete file via GitHub API
      # Use the octokit/request-action for a cleaner way to interact with the GitHub API.
      uses: octokit/request-action@v2.x
      with:
        route: DELETE /repos/{owner}/{repo}/contents/{path}
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        path: ${{ github.event.inputs.file_to_delete }}
        ref: ${{ github.ref }} # Target the branch where the file should be deleted (e.g., main)
        mediaType: '{"format": "json"}' # Specify JSON format for the request body
        data: |
          {
            "message": "워크플로우를 통해 오류 파일 삭제: ${{ github.event.inputs.file_to_delete }}",
            "sha": "${{ steps.get_sha.outputs.file_sha }}"
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
