name: Delete Failed Workflow Runs

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required for deleting and disabling workflow runs
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Delete and disable failed workflow runs
        run: python scripts/delete_and_disable_failed_workflows.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
