name: 🧹 Delete all .md files

on:
  workflow_dispatch:

jobs:
  delete-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout springboot repository
        uses: actions/checkout@v4
        with:
          repository: 'davidkims/springboot'
          # 필요한 경우, 아래 줄의 주석을 해제하고 토큰 추가
          # token: ${{ secrets.YOUR_GITHUB_TOKEN }}

      - name: 🗑️ Delete all *.md files (all directories)
        run: |
          echo "echo '[🗑️] .md 확장자로 끝나는 모든 파일 삭제 시작...'"
          echo '[🗑️] .md 확장자로 끝나는 모든 파일 삭제 시작...'
          find . -type f -name '*.md' -print -exec echo "rm {}" \; -exec rm {} \;
          echo "echo '[🗑️] 삭제 완료!'"
          echo '[🗑️] 삭제 완료!'
