# 파일 경로: .github/workflows/download-security-regulations.yml

name: Download Security Regulations

on:
  # 매주 월요일 02:00 UTC (Asia/Seoul 기준 매주 월요일 11:00)
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  download-regulations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare regulations directory
        run: mkdir -p regulations

      - name: Download CVSS v3.1 Specification (CVC → CVSS)
        continue-on-error: true
        run: |
          URL="https://www.first.org/cvss/v3-1/specification-document"
          OUT="regulations/CVSS_v3.1_Specification_$(date +'%Y-%m-%d').pdf"
          if curl -fSL "$URL" -o "$OUT"; then
            echo "✅ CVSS spec downloaded to $OUT"
          else
            echo "⚠️ CVSS spec not found at $URL, skipping."
          fi
        # CVSS v3.1 Specification Document :contentReference[oaicite:0]{index=0}

      - name: Download CVE Modified Feed (JSON 1.1)
        continue-on-error: true
        run: |
          URL="https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz"
          OUT_GZ="regulations/CVE_Modified_$(date +'%Y-%m-%d').json.gz"
          if curl -fSL "$URL" -o "$OUT_GZ"; then
            echo "✅ CVE feed downloaded"
            gunzip -f "$OUT_GZ"
          else
            echo "⚠️ CVE feed not available, skipping."
          fi
        # NVD JSON 1.1 CVE-Modified Feed :contentReference[oaicite:1]{index=1}

      - name: Download ISRM Guidelines (NIST SP 800-30 Rev.1)
        continue-on-error: true
        run: |
          URL="https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-30r1.pdf"
          OUT="regulations/NIST_SP800-30_Rev1_$(date +'%Y-%m-%d').pdf"
          if curl -fSL "$URL" -o "$OUT"; then
            echo "✅ ISRM guidelines downloaded to $OUT"
          else
            echo "⚠️ ISRM guidelines not found at $URL, skipping."
          fi
        # NIST SP 800-30 Rev.1 Guide for Conducting Risk Assessments :contentReference[oaicite:2]{index=2}

      - name: Commit & push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add regulations
          git diff --quiet || git commit -m "chore: update CVSS, CVE, ISRM regulations"
          git push
