name: Generate Repository Blog

on:
  schedule:
    - cron: '0 0 */999 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate blog
        run: python scripts/generate_blog.py
      - name: Commit blog
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add BLOG.md
          git commit -m "chore: update generated blog" || echo "No changes"
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
