name: MySQL Latest Version Upgrade

on:
  workflow_dispatch: # 수동으로 워크플로우 실행 가능
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: '0 0 * * *' # 매일 자정 (UTC)에 실행 (선택 사항)

jobs:
  upgrade-mysql:
    runs-on: ubuntu-latest # GitHub Actions 러너 운영체제 (Ubuntu 최신 버전)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 저장소 코드 체크아웃

    - name: Set up MySQL APT repository
      run: |
        # MySQL APT 저장소 추가 (Ubuntu용)
        # 최신 MySQL 버전을 얻기 위해 공식 저장소를 사용합니다.
        # 자세한 내용은 MySQL 공식 문서 참조: https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/
        sudo apt-get update
        sudo apt-get install -y apt-transport-https # HTTPS를 통한 패키지 다운로드를 위해 필요
        
        # MySQL APT Repository Configuration Tool 다운로드 및 설치
        wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb
        sudo dpkg -i mysql-apt-config_0.8.29-1_all.deb
        
        # 설치 과정에서 MySQL 버전 선택 프롬프트가 나타납니다.
        # 기본값으로 최신 버전을 선택하도록 스크립트를 자동화합니다.
        # dpkg-reconfigure 명령으로 사용자 상호작용 없이 기본값을 선택
        # MySQL 8.0을 최신 안정 버전으로 간주하고 선택
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure mysql-apt-config
        
        # apt 캐시 업데이트
        sudo apt-get update

    - name: Stop MySQL service (if running)
      run: |
        # 기존 MySQL 서비스가 실행 중이라면 중지
        sudo systemctl stop mysql || true
        # `|| true`는 서비스가 이미 중지되어 있어도 오류를 발생시키지 않도록 합니다.

    - name: Install/Upgrade MySQL Server to latest version
      run: |
        # MySQL 서버 및 클라이언트 최신 버전 설치/업그레이드
        # -y 옵션으로 모든 프롬프트에 'yes' 응답
        sudo apt-get install -y mysql-server mysql-client
        
        # 설치 후 MySQL 서비스가 자동으로 시작되는지 확인
        sudo systemctl status mysql

    - name: Run mysql_upgrade
      run: |
        # MySQL 서버 업그레이드 유틸리티 실행
        # 이는 시스템 테이블을 확인하고 필요에 따라 업그레이드하며
        # 비호환성 문제를 해결하는 데 도움이 됩니다.
        # MySQL 8.0 이상에서는 대부분 자동으로 처리되지만, 안전을 위해 실행하는 것이 좋습니다.
        # root 사용자 비밀번호를 설정해야 할 경우, 환경 변수 또는 secrets를 사용하세요.
        # 여기서는 기본적으로 비밀번호가 없는 경우를 가정합니다.
        # 만약 root 비밀번호가 있다면, `-p` 옵션을 사용하고 secrets로 비밀번호를 넘겨야 합니다.
        # 예: `mysql_upgrade --user=root --password="${{ secrets.MYSQL_ROOT_PASSWORD }}"`
        sudo mysql_upgrade --force || true
        
        # MySQL 서비스 재시작하여 변경 사항 적용
        sudo systemctl restart mysql

    - name: Verify MySQL version
      run: |
        # MySQL 서버 버전 확인
        mysql --version
        echo "MySQL upgrade completed successfully!"
