# 이 YAML 파일은 MySQL 데이터베이스 백업을 수행하는 CI/CD 작업을 정의합니다.
# 'Access denied' 오류를 포함한 일반적인 문제를 해결하도록 설계되었습니다.

name: MySQL Database Backup and Upload

on:
  # 이 워크플로우가 언제 실행될지 정의합니다.
  workflow_dispatch: # 수동으로 워크플로우를 실행할 수 있도록 합니다.
  # schedule:
  #   - cron: '0 2 * * *' # 매일 UTC 2시에 실행되도록 예약하려면 이 주석을 해제하세요.

jobs:
  backup_mysql:
    runs-on: ubuntu-latest # 작업을 실행할 환경을 지정합니다. (예: GitHub Actions의 Ubuntu 러너)

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v4 # 현재 저장소 코드를 러너로 가져옵니다.

    - name: MySQL 백업 수행
      env:
        # MySQL 연결 상세 정보
        MYSQL_HOST: localhost # MySQL 호스트 이름 (기본값: localhost)
        MYSQL_PORT: 3306      # MySQL 포트 번호 (기본값: 3306)
        MYSQL_USER: root      # MySQL 사용자 이름 (기본값: root)

        # ====================================================================
        # ⭐⭐⭐ 중요: MySQL 비밀번호 설정 ⭐⭐⭐
        # 아래 두 가지 방법 중 정확히 하나만 선택하여 'MYSQL_PASSWORD'를 설정해야 합니다.
        # 둘 다 주석 처리하거나, 둘 다 활성화해서는 안 됩니다.
        # ====================================================================

        # ✅ 방법 1 (권장 - 보안): CI/CD 환경의 '비밀(secrets)' 사용
        #    사용하시는 CI/CD 플랫폼(예: GitHub Actions)의 저장소 설정으로 이동하여
        #    'Secrets' 탭에서 'MYSQL_ROOT_PASSWORD'라는 이름의 비밀을 생성하고,
        #    여기에 실제 MySQL root 비밀번호를 입력하십시오.
        #    이 방법을 사용하는 경우, 아래 '방법 2' 줄은 반드시 주석 처리해야 합니다.
        MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

        # ❌ 방법 2 (보안상 비권장 - 테스트 목적으로만 사용): 여기에 실제 비밀번호를 직접 입력
        #    secrets 설정에 어려움이 있거나 빠른 테스트가 필요한 경우에만 사용하십시오.
        #    이 방법을 사용하는 경우, 위의 '방법 1' 줄은 반드시 주석 처리해야 합니다.
        #    'YOUR_ACTUAL_MYSQL_ROOT_PASSWORD'를 실제 MySQL root 비밀번호로 교체하십시오.
        # MYSQL_PASSWORD: YOUR_ACTUAL_MYSQL_ROOT_PASSWORD

        # 백업할 특정 데이터베이스 이름 (선택 사항)
        # 이 변수를 비워두면 모든 데이터베이스를 백업합니다.
        # 예: MYSQL_DATABASE: your_specific_database_name
        MYSQL_DATABASE: "" # 특정 데이터베이스를 백업하려면 여기에 이름을 입력하세요.

      run: |
        #!/bin/bash
        set -x # 이 줄을 추가하여 스크립트 실행 과정을 자세히 출력하고 환경 변수 확인에 도움을 줍니다.

        # 타임스탬프를 포함한 백업 파일명 정의
        BACKUP_FILENAME="mysql_backup_$(date +%Y%m%d_%H%M%S).sql"

        echo "--- MySQL 백업 스크립트 시작 ---"
        echo "백업 파일명: $BACKUP_FILENAME"
        echo "MySQL 호스트: $MYSQL_HOST"
        echo "MySQL 포트: $MYSQL_PORT"
        echo "MySQL 사용자: $MYSQL_USER"
        if [ -n "$MYSQL_DATABASE" ]; then
          echo "백업할 데이터베이스: $MYSQL_DATABASE"
        else
          echo "모든 데이터베이스를 백업합니다."
        fi

        # 현재 MYSQL_PASSWORD 값을 출력하여 확인 (set -x와 함께 디버깅에 유용)
        # 이 값은 secrets 사용 시 보안상 마스킹될 수 있습니다 (예: ***)
        echo "현재 MYSQL_PASSWORD 값: '$MYSQL_PASSWORD'"

        # MYSQL_PASSWORD 환경 변수가 비어 있는지 확인
        # 또는 플레이스홀더 값인지 확인 (직접 입력 방식 사용 시)
        if [ -z "$MYSQL_PASSWORD" ] || [ "$MYSQL_PASSWORD" == "YOUR_ACTUAL_MYSQL_ROOT_PASSWORD" ]; then
          echo "⭐⭐⭐ 치명적 오류: MySQL 비밀번호가 올바르게 설정되지 않았습니다. ⭐⭐⭐"
          echo "--------------------------------------------------------------------------------"
          echo "이 오류는 스크립트 내부의 문제가 아니라, CI/CD 환경에서 'MYSQL_PASSWORD' 변수가"
          echo "제대로 채워지지 않았기 때문에 발생합니다."
          echo ""
          echo "아래 단계를 따라 CI/CD 환경의 비밀(secrets) 설정을 다시 확인하십시오:"
          echo "1. GitHub 저장소로 이동합니다."
          echo "2. 'Settings' 탭을 클릭합니다."
          echo "3. 왼쪽 사이드바에서 'Secrets and variables' 아래의 'Actions'를 클릭합니다."
          echo "4. 'Repository secrets' 탭을 클릭합니다."
          echo "5. 'MYSQL_ROOT_PASSWORD'라는 이름의 비밀이 존재하는지 확인합니다."
          echo "   - 만약 존재하지 않는다면, 'New repository secret' 버튼을 클릭하여 새로 생성합니다."
          echo "   - 이름은 'MYSQL_ROOT_PASSWORD'로 정확히 입력하고, 값에는 실제 MySQL root 비밀번호를 입력합니다."
          echo "   - 만약 존재하지만 값이 비어있거나 잘못되었다면, 해당 비밀을 업데이트합니다."
          echo ""
          echo "방법 2 (직접 입력)를 선택했다면, YAML 파일 내의 'YOUR_ACTUAL_MYSQL_ROOT_PASSWORD'를"
          echo "실제 비밀번호로 교체하고, 방법 1 줄이 주석 처리되어 있는지 확인하십시오."
          echo "--------------------------------------------------------------------------------"
          exit 1 # 스크립트 종료
        fi

        # MYSQL_PWD 환경 변수 사용: mysqldump에 비밀번호를 안전하게 전달하는 표준 방법
        # 이렇게 하면 명령줄 기록에 비밀번호가 직접 노출되는 것을 방지할 수 있습니다.
        export MYSQL_PWD="$MYSQL_PASSWORD"

        # 백업 수행
        if [ -z "$MYSQL_DATABASE" ]; then
          echo "실행 명령: mysqldump --all-databases --host=\"$MYSQL_HOST\" --port=\"$MYSQL_PORT\" --user=\"$MYSQL_USER\" > \"$BACKUP_FILENAME\""
          mysqldump --all-databases \
                    --host="$MYSQL_HOST" \
                    --port="$MYSQL_PORT" \
                    --user="$MYSQL_USER" > "$BACKUP_FILENAME"
        else
          echo "실행 명령: mysqldump --host=\"$MYSQL_HOST\" --port=\"$MYSQL_PORT\" --user=\"$MYSQL_USER\" \"$MYSQL_DATABASE\" > \"$BACKUP_FILENAME\""
          mysqldump --host="$MYSQL_HOST" \
                    --port="$MYSQL_PORT" \
                    --user="$MYSQL_USER" \
                    "$MYSQL_DATABASE" > "$BACKUP_FILENAME"
        fi

        # mysqldump 명령의 종료 코드 확인
        if [ $? -eq 0 ]; then
          echo "MySQL 백업이 성공적으로 생성되었습니다: $BACKUP_FILENAME"
          # 백업 파일이 생성되었는지 확인
          if [ -f "$BACKUP_FILENAME" ]; then
            echo "백업 파일 크기: $(du -h "$BACKUP_FILENAME" | awk '{print $1}')"
          else
            echo "경고: 백업 파일($BACKUP_FILENAME)이 생성되지 않았거나 찾을 수 없습니다."
            exit 1 # 파일이 없으면 오류로 처리
          fi
        else
          echo "오류: MySQL 백업에 실패했습니다."
          echo "위의 mysqldump 오류 메시지를 확인하십시오. (예: 'Access denied' 또는 'Unknown database')"
          exit 1 # 스크립트 종료
        fi
        echo "--- MySQL 백업 스크립트 종료 ---"

    - name: 백업 파일을 아티팩트로 업로드
      uses: actions/upload-artifact@v4
      with:
        name: mysql-backup
        path: "*.sql" # 현재 디렉토리의 모든 .sql 파일을 아티팩트로 업로드합니다.
        retention-days: 7 # 아티팩트를 7일 동안 보존합니다.
