name: Rust CI

on:
  push:        { branches: [ main ] }
  pull_request:{ branches: [ main ] }

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Locate Cargo.toml
        id: locate
        run: |
          if [ -f Cargo.toml ]; then
            echo "dir=." >> $GITHUB_OUTPUT
          elif [ -f springboot/Cargo.toml ]; then
            echo "dir=springboot" >> $GITHUB_OUTPUT
          else
            echo "::error ::Could not find Cargo.toml in either ./ or ./springboot/"
            exit 1
          fi

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: ${{ steps.locate.outputs.dir }}/target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Build
        run: |
          cd ${{ steps.locate.outputs.dir }}
          cargo build --verbose

      - name: Test
        run: |
          cd ${{ steps.locate.outputs.dir }}
          cargo test --verbose
