# .github/workflows/update-agents.yml
name: Update Self-Hosted Agents List

on:
  schedule:
    # 매주 일요일 00:00 (UTC)에 실행
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update-agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get self-hosted runners
        id: get_runners
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 레포지토리의 self-hosted runner 목록 조회
            const resp = await github.rest.actions.listSelfHostedRunnersForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            // 이름만 추출하여 줄바꿈으로 연결
            return resp.data.runners.map(r => r.name).join('\n');

      - name: Update agents.md
        run: |
          # 헤더 작성
          echo "# Self-Hosted Runner Agents" > agents.md
          echo "" >> agents.md
          # API 결과를 한 줄씩 추가
          while IFS= read -r runner; do
            echo "- $runner" >> agents.md
          done <<< "${{ steps.get_runners.outputs.result }}"

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 변경사항이 있을 때만 커밋
          if git diff --exit-code; then
            echo "No changes to commit"
          else
            git add agents.md
            git commit -m "chore: update self-hosted runner agents list"
            git push
          fi
