name: Update Program Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 00:00 UTC

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Refresh data for all programs
        run: bash workflow/update_all_data.sh
